#!/bin/bash

set -euo pipefail

if ! dpkg -s proxmox-widget-toolkit | grep -q 'installed'; then
	exit 0
fi

# use dpkg -V to verify the package; if we haven't previously modified the file, then do so
if ! dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$' ; then
	echo 'Removing subscription nag from UI...'
	sed -i '/data\.status.*{/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
fi
